[DEFAULT]
debian-branch = debian/latest
upstream-branch = upstream/latest
dist = DEP14

# Use pristine tar to improve supply chain security and auditability
pristine-tar = True

# Lax requirement to use branch name 'debian/latest' so that git-buildpackage
# will always build using the currently checked out branch as the Debian branch.
# This makes it easier for contributors to work with feature and bugfix
# branches.
ignore-branch = True

# If upstream publishes tarball signatures, git-buildpackage will by default
# import and use the them. Change this to 'on' to make 'gbp import-orig' abort
# if the signature is not found or is not valid.
#
# Most Go packages don't publish signatures for the tarball releases, so this is
# not enabled by default.
#upstream-signatures = on

# Ensure the Debian maintainer signs git tags automatically
sign-tags = True
